.TH "src/app/namir_types Directory Reference" 3 "Wed Mar 8 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/app/namir_types Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccount\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaccount\&.h\fP"
.br
.ti -1c
.RI "file \fBborder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBborder\&.h\fP"
.br
.ti -1c
.RI "file \fBBorderItem\&.qml\fP"
.br
.ti -1c
.RI "file \fBhistory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhistory\&.h\fP"
.br
.ti -1c
.RI "file \fBobject\&.cpp\fP"
.br
.ti -1c
.RI "file \fBobject\&.h\fP"
.br
.ti -1c
.RI "file \fBoperate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBoperate\&.h\fP"
.br
.ti -1c
.RI "file \fBPage\&.qml\fP"
.br
.ti -1c
.RI "file \fBroom\&.cpp\fP"
.br
.ti -1c
.RI "file \fBroom\&.h\fP"
.br
.ti -1c
.RI "file \fBstyle\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstyle\&.h\fP"
.br
.ti -1c
.RI "file \fBStyle\&.qml\fP"
.br
.in -1c
