.TH "src/tree/include/account.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/account.h
.SH SYNOPSIS
.br
.PP
\fC#include 'limb_id\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccountData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBAccountData\fP > \fBAccount\fP"
.br
.ti -1c
.RI "typedef QList< \fBAccount\fP > \fBAccountList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBAccountData\fP> \fBAccount\fP"

.PP
Definition at line 40 of file account\&.h\&.
.SS "typedef QList<\fBAccount\fP> \fBAccountList\fP"

.PP
Definition at line 41 of file account\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
