.TH "AccountData" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccountData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <account\&.h>\fP
.PP
Inherits \fBLimbIdData\fP\&.
.PP
Inherited by \fBAuthData\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBloginChanged\fP ()"
.br
.ti -1c
.RI "void \fBusernameChanged\fP ()"
.br
.ti -1c
.RI "void \fBuserIdChanged\fP ()"
.br
.ti -1c
.RI "void \fBdescriptionChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccountData\fP ()=default"
.br
.ti -1c
.RI "QString \fBlogin\fP () const"
.br
.ti -1c
.RI "QString \fBusername\fP () const"
.br
.ti -1c
.RI "uint \fBuserId\fP () const"
.br
.ti -1c
.RI "QString \fBdescription\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBlogin\fP"
.br
.ti -1c
.RI "QString \fBusername\fP"
.br
.ti -1c
.RI "uint \fBuserId\fP"
.br
.ti -1c
.RI "QString \fBdescription\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString \fBm_login\fP"
.br
.ti -1c
.RI "QString \fBm_username\fP"
.br
.ti -1c
.RI "uint \fBm_userId\fP"
.br
.ti -1c
.RI "QString \fBm_description\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBAccountData\fP &a)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBAccountData\fP &a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file account\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AccountData::AccountData ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QString AccountData::description () const"

.PP
Definition at line 18 of file account\&.cpp\&.
.SS "void AccountData::descriptionChanged ()\fC [signal]\fP"

.SS "QString AccountData::login () const"

.PP
Definition at line 3 of file account\&.cpp\&.
.SS "void AccountData::loginChanged ()\fC [signal]\fP"

.SS "uint AccountData::userId () const"

.PP
Definition at line 13 of file account\&.cpp\&.
.SS "void AccountData::userIdChanged ()\fC [signal]\fP"

.SS "QString AccountData::username () const"

.PP
Definition at line 8 of file account\&.cpp\&.
.SS "void AccountData::usernameChanged ()\fC [signal]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBAccountData\fP & a)\fC [friend]\fP"

.PP
Definition at line 29 of file account\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBAccountData\fP & a)\fC [friend]\fP"

.PP
Definition at line 23 of file account\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString AccountData::m_description\fC [private]\fP"

.PP
Definition at line 37 of file account\&.h\&.
.SS "QString AccountData::m_login\fC [private]\fP"

.PP
Definition at line 34 of file account\&.h\&.
.SS "uint AccountData::m_userId\fC [private]\fP"

.PP
Definition at line 36 of file account\&.h\&.
.SS "QString AccountData::m_username\fC [private]\fP"

.PP
Definition at line 35 of file account\&.h\&.
.SH "Property Documentation"
.PP 
.SS "QString AccountData::description\fC [read]\fP"

.PP
Definition at line 41 of file account\&.h\&.
.SS "QString AccountData::login\fC [read]\fP"

.PP
Definition at line 41 of file account\&.h\&.
.SS "uint AccountData::userId\fC [read]\fP"

.PP
Definition at line 41 of file account\&.h\&.
.SS "QString AccountData::username\fC [read]\fP"

.PP
Definition at line 41 of file account\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
