.TH "src/tree/account.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/account.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'account\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBAccountData\fP &a)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBAccountData\fP &a)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBAccountData\fP & a)"

.PP
Definition at line 29 of file account\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBAccountData\fP & a)"

.PP
Definition at line 23 of file account\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
