.TH "Adding" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adding
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adding\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBleftChanged\fP ()"
.br
.ti -1c
.RI "void \fBrightChanged\fP ()"
.br
.ti -1c
.RI "void \fBtopChanged\fP ()"
.br
.ti -1c
.RI "void \fBbottomChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBleft\fP () const"
.br
.ti -1c
.RI "void \fBsetLeft\fP (double newLeft)"
.br
.ti -1c
.RI "double \fBright\fP () const"
.br
.ti -1c
.RI "void \fBsetRight\fP (double newRight)"
.br
.ti -1c
.RI "double \fBtop\fP () const"
.br
.ti -1c
.RI "void \fBsetTop\fP (double newTop)"
.br
.ti -1c
.RI "double \fBbottom\fP () const"
.br
.ti -1c
.RI "void \fBsetBottom\fP (double newBottom)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBleft\fP"
.br
.ti -1c
.RI "double \fBright\fP"
.br
.ti -1c
.RI "double \fBtop\fP"
.br
.ti -1c
.RI "double \fBbottom\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBm_left\fP"
.br
.ti -1c
.RI "double \fBm_right\fP"
.br
.ti -1c
.RI "double \fBm_top\fP"
.br
.ti -1c
.RI "double \fBm_bottom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file adding\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double Adding::bottom () const"

.PP
Definition at line 30 of file adding\&.cpp\&.
.SS "void Adding::bottomChanged ()\fC [signal]\fP"

.SS "double Adding::left () const"

.PP
Definition at line 3 of file adding\&.cpp\&.
.SS "void Adding::leftChanged ()\fC [signal]\fP"

.SS "double Adding::right () const"

.PP
Definition at line 12 of file adding\&.cpp\&.
.SS "void Adding::rightChanged ()\fC [signal]\fP"

.SS "void Adding::setBottom (double newBottom)"

.PP
Definition at line 31 of file adding\&.cpp\&.
.SS "void Adding::setLeft (double newLeft)"

.PP
Definition at line 4 of file adding\&.cpp\&.
.SS "void Adding::setRight (double newRight)"

.PP
Definition at line 13 of file adding\&.cpp\&.
.SS "void Adding::setTop (double newTop)"

.PP
Definition at line 22 of file adding\&.cpp\&.
.SS "double Adding::top () const"

.PP
Definition at line 21 of file adding\&.cpp\&.
.SS "void Adding::topChanged ()\fC [signal]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double Adding::m_bottom\fC [private]\fP"

.PP
Definition at line 37 of file adding\&.h\&.
.SS "double Adding::m_left\fC [private]\fP"

.PP
Definition at line 34 of file adding\&.h\&.
.SS "double Adding::m_right\fC [private]\fP"

.PP
Definition at line 35 of file adding\&.h\&.
.SS "double Adding::m_top\fC [private]\fP"

.PP
Definition at line 36 of file adding\&.h\&.
.SH "Property Documentation"
.PP 
.SS "double Adding::bottom\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file adding\&.h\&.
.SS "double Adding::left\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file adding\&.h\&.
.SS "double Adding::right\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file adding\&.h\&.
.SS "double Adding::top\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file adding\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
