.TH "src/app/adding.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/app/adding.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtQml/QQmlEngine>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdding\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
