.TH "src/tree/auth.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/auth.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'auth\&.h'\fP
.br
\fC#include 'storage\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBAuthData\fP &au)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBAuthData\fP &au)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBAuthData\fP & au)"

.PP
Definition at line 13 of file auth\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBAuthData\fP & au)"

.PP
Definition at line 9 of file auth\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
