.TH "src/tree/include/auth.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/auth.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSharedPointer>\fP
.br
\fC#include 'account\&.h'\fP
.br
\fC#include <QtCore/QObject>\fP
.br
\fC#include 'room\&.h'\fP
.br
\fC#include <QDataStream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBAuthData\fP > \fBAuth\fP"
.br
.ti -1c
.RI "typedef QList< \fBAuth\fP > \fBAuthList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBAuthData\fP> \fBAuth\fP"

.PP
Definition at line 34 of file auth\&.h\&.
.SS "typedef QList<\fBAuth\fP> \fBAuthList\fP"

.PP
Definition at line 35 of file auth\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
