.TH "Correction" 3 "Wed Mar 8 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Correction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <correction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCorrection\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFieldList\fP \fBm_fields\fP"
.br
.ti -1c
.RI "\fBAccount\fP \fBm_sender\fP"
.br
.ti -1c
.RI "QDateTime \fBm_dTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file correction\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Correction::Correction ()"

.SH "Member Data Documentation"
.PP 
.SS "QDateTime Correction::m_dTime\fC [private]\fP"

.PP
Definition at line 13 of file correction\&.h\&.
.SS "\fBFieldList\fP Correction::m_fields\fC [private]\fP"

.PP
Definition at line 11 of file correction\&.h\&.
.SS "\fBAccount\fP Correction::m_sender\fC [private]\fP"

.PP
Definition at line 12 of file correction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
