.TH "src/tree/include/correction.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/correction.h
.SH SYNOPSIS
.br
.PP
\fC#include 'field\&.h'\fP
.br
\fC#include 'account\&.h'\fP
.br
\fC#include <QtCore/QDateTime>\fP
.br
\fC#include 'limb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCorrectionData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBCorrectionData\fP > \fBCorrection\fP"
.br
.ti -1c
.RI "typedef QList< \fBCorrection\fP > \fBCorrectionList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBCorrectionData\fP> \fBCorrection\fP"

.PP
Definition at line 27 of file correction\&.h\&.
.SS "typedef QList<\fBCorrection\fP> \fBCorrectionList\fP"

.PP
Definition at line 28 of file correction\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
