.TH "economy::Currencies::Single" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
economy::Currencies::Single
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBenums::Currency\fP \fBm_enum\fP"
.br
.ti -1c
.RI "std::string \fBm_full\fP"
.br
.ti -1c
.RI "std::string \fBm_short\fP"
.br
.ti -1c
.RI "\fBenums::Continent\fP \fBm_continent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 557 of file enum\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBenums::Continent\fP economy::Currencies::Single::m_continent"

.PP
Definition at line 561 of file enum\&.h\&.
.SS "\fBenums::Currency\fP economy::Currencies::Single::m_enum"

.PP
Definition at line 558 of file enum\&.h\&.
.SS "std::string economy::Currencies::Single::m_full"

.PP
Definition at line 559 of file enum\&.h\&.
.SS "std::string economy::Currencies::Single::m_short"

.PP
Definition at line 560 of file enum\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
