.TH "src/tree/enum.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/enum.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'enum\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBenums\fP"
.br
.RI "\\inmodule stem "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
