.TH "doxygen-awesome-css/include/MyLibrary/example.hpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doxygen-awesome-css/include/MyLibrary/example.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::Example\fP"
.br
.RI "\fBExample\fP class to demonstrate the features of the custom CSS\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMyLibrary\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMyLibrary::Color\fP "
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
