.TH "src/tree/field.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/field.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'field\&.h'\fP
.br
\fC#include 'spysok\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBFieldData\fP &f)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBFieldData\fP &f)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBFieldData\fP & f)"

.PP
Definition at line 29 of file field\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBFieldData\fP & f)"

.PP
Definition at line 24 of file field\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
