.TH "src/tree/history.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/history.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'history\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBHistory\fP &his)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBHistory\fP &his)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBHistory\fP & his)"

.PP
Definition at line 8 of file history\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBHistory\fP & his)"

.PP
Definition at line 4 of file history\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
