.TH "LimbData" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LimbData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <limb\&.h>\fP
.PP
Inherits QObject\&.
.PP
Inherited by \fBFieldData\fP, and \fBLimbIdData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLimbData\fP (QSharedPointer< \fBLimbData\fP > parent)"
.br
.ti -1c
.RI "\fBLimbData\fP (QObject *parent=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file limb\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LimbData::LimbData (QSharedPointer< \fBLimbData\fP > parent)"

.PP
Definition at line 3 of file limb\&.cpp\&.
.SS "LimbData::LimbData (QObject * parent = \fCnullptr\fP)"

.PP
Definition at line 9 of file limb\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
