.TH "src/tree/include/limb.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/limb.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QSharedPointer>\fP
.br
\fC#include <QtCore/QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLimbData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBLimbData\fP > \fBLimb\fP"
.br
.ti -1c
.RI "typedef QList< \fBLimb\fP > \fBLimbList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBLimbData\fP> \fBLimb\fP"

.PP
Definition at line 15 of file limb\&.h\&.
.SS "typedef QList<\fBLimb\fP> \fBLimbList\fP"

.PP
Definition at line 16 of file limb\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
