.TH "LimbIdData" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LimbIdData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <limb_id\&.h>\fP
.PP
Inherits \fBLimbData\fP\&.
.PP
Inherited by \fBAccountData\fP, \fBCorrectionData\fP, \fBRoomAboutData\fP, \fBRulesData\fP, \fBSpysokData\fP, and \fBUnitData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLimbIdData\fP (\fBLimb\fP parent)"
.br
.ti -1c
.RI "\fBLimbIdData\fP (QSharedPointer< \fBLimbIdData\fP > parent)"
.br
.ti -1c
.RI "\fBLimbIdData\fP (QObject *parent=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file limb_id\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LimbIdData::LimbIdData (\fBLimb\fP parent)"

.PP
Definition at line 3 of file limb_id\&.cpp\&.
.SS "LimbIdData::LimbIdData (QSharedPointer< \fBLimbIdData\fP > parent)"

.PP
Definition at line 8 of file limb_id\&.cpp\&.
.SS "LimbIdData::LimbIdData (QObject * parent = \fCnullptr\fP)"

.PP
Definition at line 13 of file limb_id\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
