.TH "LinkKey" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <link\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinkKey\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBLinkKey\fP lk)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBLinkKey\fP lk)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file link\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LinkKey::LinkKey ()"

.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBLinkKey\fP lk)\fC [friend]\fP"

.SS "QDataStream& operator>> (QDataStream & s, \fBLinkKey\fP lk)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
