.TH "src/tree/include/link.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/link.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSharedPointer>\fP
.br
\fC#include 'sap\&.h'\fP
.br
\fC#include 'enum\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLink\fP"
.br
.ti -1c
.RI "class \fBLinkKey\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBLink\fP *const \fBLinkPtr\fP"
.br
.ti -1c
.RI "typedef \fBLinkKey\fP *const \fBLinkKeyPtr\fP"
.br
.ti -1c
.RI "typedef QList< \fBLink\fP * > \fBLinkList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBLinkKey\fP* const \fBLinkKeyPtr\fP"

.PP
Definition at line 9 of file link\&.h\&.
.SS "typedef QList<\fBLink\fP*> \fBLinkList\fP"

.PP
Definition at line 54 of file link\&.h\&.
.SS "typedef \fBLink\fP* const \fBLinkPtr\fP"

.PP
Definition at line 8 of file link\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
