.TH "namir::qml" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
namir::qml
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBorder\fP"
.br
.ti -1c
.RI "class \fBStyle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
