.TH "namir::qml::Style" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
namir::qml::Style
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <style\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBpanelChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBpanel\fP () const"
.br
.ti -1c
.RI "void \fBsetPanel\fP (double newPanel)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBpanel\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBm_panel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file style\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "double namir::qml::Style::panel () const"

.PP
Definition at line 3 of file style\&.cpp\&.
.SS "void namir::qml::Style::panelChanged ()\fC [signal]\fP"

.SS "void namir::qml::Style::setPanel (double newPanel)"

.PP
Definition at line 8 of file style\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double namir::qml::Style::m_panel\fC [private]\fP"

.PP
Definition at line 22 of file style\&.h\&.
.SH "Property Documentation"
.PP 
.SS "double namir::qml::Style::panel\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 1 of file style\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
