.TH "namir::Variant" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
namir::Variant
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <room\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvariant\fP \fBvar\fP () const"
.br
.ti -1c
.RI "\fBVariants\fP \fBvar_type\fP () const"
.br
.ti -1c
.RI "const \fBVariant\fP & \fBvariantType\fP () const"
.br
.ti -1c
.RI "\fBvariant\fP \fBvar\fP () const"
.br
.ti -1c
.RI "\fBVariants\fP \fBvar_type\fP () const"
.br
.ti -1c
.RI "const \fBVariant\fP & \fBvariantType\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBvariant\fP \fBm_var\fP"
.br
.ti -1c
.RI "\fBVariants\fP \fBm_var_type\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBVariant\fP &op)"
.br
.ti -1c
.RI "std::wostream & \fBoperator<<\fP (std::wostream &os, const \fBVariant\fP &op)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &stream, const \fBVariant\fP &op)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBVariant\fP &op)"
.br
.ti -1c
.RI "std::wostream & \fBoperator<<\fP (std::wostream &os, const \fBVariant\fP &op)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &stream, const \fBVariant\fP &op)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file room\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvariant\fP namir::Variant::var () const\fC [inline]\fP"

.PP
Definition at line 27 of file room\&.cpp\&.
.SS "\fBvariant\fP namir::Variant::var () const\fC [inline]\fP"

.PP
Definition at line 27 of file room\&.h\&.
.SS "\fBVariants\fP namir::Variant::var_type () const\fC [inline]\fP"

.PP
Definition at line 28 of file room\&.cpp\&.
.SS "\fBVariants\fP namir::Variant::var_type () const\fC [inline]\fP"

.PP
Definition at line 28 of file room\&.h\&.
.SS "const \fBVariant\fP& namir::Variant::variantType () const\fC [inline]\fP"

.PP
Definition at line 30 of file room\&.cpp\&.
.SS "const \fBVariant\fP& namir::Variant::variantType () const\fC [inline]\fP"

.PP
Definition at line 30 of file room\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & stream, const \fBVariant\fP & op)\fC [friend]\fP"

.SS "QDataStream& operator<< (QDataStream & stream, const \fBVariant\fP & op)\fC [friend]\fP"

.SS "std:: ostream& operator<< (std::ostream & os, const \fBVariant\fP & op)\fC [friend]\fP"

.SS "std:: ostream& operator<< (std::ostream & os, const \fBVariant\fP & op)\fC [friend]\fP"

.SS "std::wostream& operator<< (std::wostream & os, const \fBVariant\fP & op)\fC [friend]\fP"

.SS "std::wostream& operator<< (std::wostream & os, const \fBVariant\fP & op)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBvariant\fP namir::Variant::m_var\fC [protected]\fP"

.PP
Definition at line 37 of file room\&.cpp\&.
.SS "\fBVariants\fP namir::Variant::m_var_type\fC [protected]\fP"

.PP
Definition at line 38 of file room\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
