.TH "src/tree/room.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/room.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'room\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBRoomData\fP &r)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBRoomData\fP &r)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBRoomData\fP & r)"

.PP
Definition at line 23 of file room\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBRoomData\fP & r)"

.PP
Definition at line 18 of file room\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
