.TH "Room" 3 "Wed Mar 8 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Room
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <room\&.h>\fP
.PP
Inherits \fBRoomAbout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoom\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QList< \fBSpysok\fP > \fBm_spysky\fP"
.br
.ti -1c
.RI "QList< \fBUnit\fP > \fBm_units\fP"
.br
.ti -1c
.RI "\fBRoom\fP * \fBm_parent\fP"
.br
.ti -1c
.RI "QList< \fBRoom\fP * > \fBm_childrens\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file room\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Room::Room ()"

.SH "Member Data Documentation"
.PP 
.SS "QList<\fBRoom\fP*> Room::m_childrens\fC [private]\fP"

.PP
Definition at line 16 of file room\&.h\&.
.SS "\fBRoom\fP* Room::m_parent\fC [private]\fP"

.PP
Definition at line 15 of file room\&.h\&.
.SS "QList<\fBSpysok\fP> Room::m_spysky\fC [private]\fP"

.PP
Definition at line 12 of file room\&.h\&.
.SS "QList<\fBUnit\fP> Room::m_units\fC [private]\fP"

.PP
Definition at line 13 of file room\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
