.TH "RoomAboutData" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoomAboutData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <room_about\&.h>\fP
.PP
Inherits \fBLimbIdData\fP\&.
.PP
Inherited by \fBRoomData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoomAboutData\fP ()=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file room_about\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RoomAboutData::RoomAboutData ()\fC [default]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
