.TH "src/tree/include/room_about.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/room_about.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSharedPointer>\fP
.br
\fC#include 'limb_id\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRoomAboutData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBRoomAboutData\fP > \fBRoomAbout\fP"
.br
.ti -1c
.RI "typedef QList< \fBRoomAbout\fP * > \fBRoomAboutList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBRoomAboutData\fP> \fBRoomAbout\fP"

.PP
Definition at line 18 of file room_about\&.h\&.
.SS "typedef QList<\fBRoomAbout\fP*> \fBRoomAboutList\fP"

.PP
Definition at line 19 of file room_about\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
