.TH "src/tree/include/room.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/room.h
.SH SYNOPSIS
.br
.PP
\fC#include 'spysok\&.h'\fP
.br
\fC#include 'room_about\&.h'\fP
.br
\fC#include <QList>\fP
.br
\fC#include 'rules\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRoomData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBRoomData\fP > \fBRoom\fP"
.br
.ti -1c
.RI "typedef QList< \fBRoom\fP > \fBRoomList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBRoomData\fP> \fBRoom\fP"

.PP
Definition at line 28 of file room\&.h\&.
.SS "typedef QList<\fBRoom\fP> \fBRoomList\fP"

.PP
Definition at line 29 of file room\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
