.TH "RulesData" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RulesData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rules\&.h>\fP
.PP
Inherits \fBLimbIdData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRulesData\fP ()=default"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBRulesData\fP &rul)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBRulesData\fP &rul)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file rules\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RulesData::RulesData ()\fC [default]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBRulesData\fP & rul)\fC [friend]\fP"

.SS "QDataStream& operator>> (QDataStream & s, \fBRulesData\fP & rul)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
