.TH "sap< t_size >" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sap< t_size > \- The sap struct Class accept only uchar numbers as parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "typedef \fBstd::conditional\fP (8 \- firstCutPos+size)"
.br
.ti -1c
.RI "\fBif\fP (firstCutPos+size >=8)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPart1\fP = firstCutPos"
.br
.ti -1c
.RI "return \fBPart1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<uint16_t t_size>
.br
struct sap< t_size >"
The sap struct Class accept only uchar numbers as parameter\&. 
.PP
Definition at line 13 of file sap\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<uint16_t t_size> \fBsap\fP< t_size >::if (firstCutPos+size >= 8)\fC [inline]\fP"

.PP
Definition at line 245 of file sap\&.h\&.
.SS "template<uint16_t t_size> typedef \fBsap\fP< t_size >::std::conditional (8 \- firstCutPos+ size)"

.SH "Member Data Documentation"
.PP 
.SS "template<uint16_t t_size> \fBsap\fP< t_size >::Part1 = firstCutPos"

.PP
Definition at line 243 of file sap\&.h\&.
.SS "template<uint16_t t_size> return \fBsap\fP< t_size >::Part1"

.PP
Definition at line 251 of file sap\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
