.TH "src/tree/include/sap.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/sap.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <string>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <array>\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsap< t_size >\fP"
.br
.RI "The sap struct Class accept only uchar numbers as parameter\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
