.TH "Spysok" 3 "Wed Mar 8 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Spysok
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spysok\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpysok\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QList< \fBUnit\fP * > \fBm_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file spysok\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Spysok::Spysok ()"

.SH "Member Data Documentation"
.PP 
.SS "QList<\fBUnit\fP*> Spysok::m_list\fC [private]\fP"

.PP
Definition at line 11 of file spysok\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
