.TH "src/tree/spysok.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/spysok.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'spysok\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBSpysok\fP &sp)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBSpysok\fP &sp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBSpysok\fP & sp)"

.PP
Definition at line 21 of file spysok\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBSpysok\fP & sp)"

.PP
Definition at line 17 of file spysok\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
