.TH "src/tree/storage.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/storage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'storage\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBStorage\fP &rage)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBStorage\fP &rage)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBStorage\fP & rage)"

.PP
Definition at line 17 of file storage\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBStorage\fP & rage)"

.PP
Definition at line 13 of file storage\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
