.TH "src/tree/unit.cpp" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/unit.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QObject>\fP
.br
\fC#include 'unit\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBUnitData\fP un)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, \fBUnitData\fP un)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, \fBUnitData\fP un)"

.PP
Definition at line 14 of file unit\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBUnitData\fP un)"

.PP
Definition at line 9 of file unit\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
