.TH "src/tree/include/unit.h" 3 "Wed Mar 15 2023" "Namir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tree/include/unit.h
.SH SYNOPSIS
.br
.PP
\fC#include 'field\&.h'\fP
.br
\fC#include 'history\&.h'\fP
.br
\fC#include 'rules\&.h'\fP
.br
\fC#include 'limb_id\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUnitData\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBUnitData\fP > \fBUnit\fP"
.br
.ti -1c
.RI "typedef QList< \fBUnit\fP > \fBUnitList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBUnitData\fP> \fBUnit\fP"

.PP
Definition at line 25 of file unit\&.h\&.
.SS "typedef QList<\fBUnit\fP> \fBUnitList\fP"

.PP
Definition at line 26 of file unit\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Namir from the source code\&.
